config/routes.rb
Rails.application.routes.draw do
  get 'pages/x'
  root 'pages#x'
  post 'pages/save_user'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def x
  end
  def save_user
  	unless params[:nombre].blank? or params[:correo].blank? or params[:edad].blank?

  		User.create(name:params[:nombre], mail:params[:correo], age:params[:edad])
  		redirect_to pages_x_path,
  		notice:"Usuario ingresado correctamente"
  	
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RepasoRails2</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <body>
	
	<div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/x.html.erb
<h1>cesar pozo miranda</h1>
<%= params.to_h %>

	<p><%= notice%></p>

<form method="POST" action="<%=pages_save_user_path%>" name="myForm">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>

	<div class="form-group">
    <label>Nombre</label>
    <input type="text" class="form-control" name="nombre" placeholder="Ingresa tu nombre">
    <div class="form-group">
    <label>Email</label>
    <input type="text" class="form-control" name="correo" placeholder="Ingresa tu correo">
    <div class="form-group">
    <label>Edad</label>
    <input type="number" class="form-control" name="edad" placeholder="Ingresa tu edad">

     <small id="emailHelp" class="form-text text-muted"></small>
  </div>

    <button type="submit" class="btn btn-primary">Submit</button>


  
</form>